before_install:
    # init xvfb
    # http://docs.travis-ci.com/user/gui-and-headless-browsers/
    - export DISPLAY=:99.0 && sh -e /etc/init.d/xvfb start
branches:
    only:
    - alpha
    - beta
    - cron
    - docker.base
    - docker.latest
    - master
    - publish
    - task
env:
    global:
    # this value is auto-created by shTravisCryptoAesEncryptYml
    - secure: e0ymTteHM5b42qv0eT+UiDMEPUR+XNmhFGSB2/HaJ7F5ARgQpXIP/OOQWc3qNb3CGdJzvPzN3gbZo1MHrtuWzCTvbt1/24smSeXwRMB4U/Gvx2BlhvBWMEDGlYU281ADvBqFwWiijD2muzIyUNZCe5VjfQxehQJertgnvXb1uX2NHXfzMxoP7mVIf0n7WaW/2JnLlYqVIaC6e/w5rSMRFGNJXdbgURjJmPiCwD/rJJ0riBmx4aoHFdgKj5vjYv2T+WuUZirSHrT46DJ61MRZ/koHL7eymaTIQU2KV3mcAfZ21TyyXGkjS06a/ILDttrcqlj/CMoIWRDJTIH7rXd8Laq++zBqyo0zZMJZ1ooS2ET13Bqzye8frfMUPI46JpwlitWT5BF0fSp0ZOdGvRv1u5inGUdOIRz6QNe/IKS/V1KeQkEyPAWOE8fjfZvLHYQVXrdcCGEQkGtNygON4x0bR62CpGqCs6FCXLPexHK2fiRskvpLX/wmZXFwom8S5n742qxzxK7ekATHIMJdeKMNUVr2kbUslYzFq4TeuhN350sckjLLyyx0bd8JAqF5/US7oJone7cfp8W3uI3mCVIj6g1s0gW8GQIWjDT18a35jvUdEP6Y0ZZDuhmXnL/Q6fAonE3mq/hYGTceflQiBOnX3FKVVb7tQ+Vk7rGCrX8zoY4= # CRYPTO_AES_KEY
    # this value is auto-created by shTravisCryptoAesEncryptYml

language:
    - node_js
node_js:
    - 6
    # - node
script:
    - npm run build-ci
services:
    - docker
# http://docs.travis-ci.com/user/workers/container-based-infrastructure
sudo:
    false
